### ISSUE TITLE
Squidwarc on Windows 10 (using npm)

### ISSUE THREAD

**Issue by mw0000** [N0taN3rd/Squidwarc#31]
I have trouble installing Squidwarc on Windows 10 (using npm).

`node-warc` directory remains empty - is that correct?

```
λ node index.js -c conf.json
module.js:550
    throw err;
    ^

Error: Cannot find module '../../node-warc/lib/requestCapturers/remoteChrome'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\m\Projekty\crawler\squidwarc\lib\crawler\chrome.js:18:24)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)


```

Also tried installing with yarn - the same effect.

**Comment by N0taN3rd** [comment]
Squidwarc uses gitmodules to bring in the `node-warc`  dependencies.

For non-windows systems Squidwarc provides a boostrap stript `boostrap.sh` which should be usable by [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

But the commands shown below should work (maybe minus cd) on plain old Windows.
```bash
git submodule init
git submodule update
yarn install install
cd node-warc
yarn install
```` 

Hopefully this helps you getting up and going
