### ISSUE TITLE
Generated WARC files fail indexing with OpenWayback cdx-indexer

### ISSUE THREAD

**Issue by peterk** [N0taN3rd/Squidwarc#32]
### Are you submitting a **bug report** or a **feature request**?
**bug report**

### What is the current behavior?
1. Set up an instance of Openwayback following [their Docker tutorial](https://github.com/iipc/openwayback/wiki/How-to-build-and-run-in-Docker).
2. Got the latest version of Squidwarc installed and ran a crawl with the sample conf.json config.
3. Moved the resulting WARC-file to the Openwayback files directory.
4. Ran the `cdx-index` command to index the WARC from inside the openwayback Docker container.  `cdx-indexer /data/files1/instagram.com\!visit_berlin-10-21-2018_1540123477677.warc > /data/index1.cdx`
5. Received error as per below:

```
Oct 21, 2018 12:08:23 PM org.archive.io.ArchiveReader$ArchiveRecordIterator hasNext
WARNING: Trying skip of failed record cleanup of {reader-identifier=/data/files1/instagram.com!visit_berlin-10-21-2018_1540123477677.warc, absolute-offset=0, WARC-Filename=instagram.com!visit_berlin-10-21-2018_1540123477677.warc, WARC-Date=2018-10-21T12:04:37Z, Content-Length=379, WARC-Record-ID=<urn:uuid:7b817fe0-d529-11e8-8ec6-391ee1fffcc8>, WARC-Type=warcinfo, Content-Type=application/warc-fields}: **Unexpected character 57(Expecting d)**
java.io.IOException: Unexpected character 57(Expecting d)
	at org.archive.io.warc.WARCReader.readExpectedChar(WARCReader.java:80)
	at org.archive.io.warc.WARCReader.gotoEOR(WARCReader.java:70)
	at org.archive.io.ArchiveReader.cleanupCurrentRecord(ArchiveReader.java:176)
	at org.archive.io.ArchiveReader$ArchiveRecordIterator.hasNext(ArchiveReader.java:449)
	at org.archive.wayback.resourcestore.indexer.ArchiveReaderCloseableIterator.hasNext(ArchiveReaderCloseableIterator.java:37)
	at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
	at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
	at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
	at org.archive.wayback.resourcestore.indexer.IndexWorker.main(IndexWorker.java:216)
``` 

### What is the expected behavior?
The captured WARC file should be properly indexed and replayable.

### What's your environment?
Squidwarc: 945e4de / 1.0
Openwayback: c49f8e720 / openwayback-core-2.4.0-SNAPSHOT

**Comment by anjackson** [comment]
I ran that WARC through JWATTools, and it reported these 'errors':

```
#
# Summary of '/Users/andy/Downloads/instagram.com!visit_berlin-10-21-2018_1540123477677.warc'
#
    Warc.isValid: false
    Warc.Records: 648
     Warc.Errors: 325
   Warc.Warnings: 0
#
# Detailed diagnosis report for '/Users/andy/Downloads/instagram.com!visit_berlin-10-21-2018_1540123477677.warc'
#
Error in '/Users/andy/Downloads/instagram.com!visit_berlin-10-21-2018_1540123477677.warc'
       Offset: 0 (0x0)
  Record Type: 'warcinfo'
         Type: INVALID_EXPECTED
       Entity: Trailing newlines
        Value: 1
     Expected: 2
Error in '/Users/andy/Downloads/instagram.com!visit_berlin-10-21-2018_1540123477677.warc'
       Offset: 645 (0x285)
  Record Type: 'metadata'
         Type: INVALID_EXPECTED
       Entity: Trailing newlines
        Value: 1
     Expected: 2
Error in '/Users/andy/Downloads/instagram.com!visit_berlin-10-21-2018_1540123477677.warc'
       Offset: 26084 (0x65e4)
  Record Type: 'request'
         Type: INVALID_EXPECTED
       Entity: Trailing newlines
        Value: 1
     Expected: 2
Error in '/Users/andy/Downloads/instagram.com!visit_berlin-10-21-2018_1540123477677.warc'
       Offset: 88776 (0x15ac8)
  Record Type: 'request'
         Type: INVALID_EXPECTED
       Entity: Trailing newlines
        Value: 1
     Expected: 2
...continues for some time...
```

Looking at the first record in an editor that shows the newlines (including the first line of the next):

```
WARC/1.0^M
WARC-Type: warcinfo^M
WARC-Date: 2018-10-21T12:04:37Z^M
WARC-Filename: instagram.com!visit_berlin-10-21-2018_1540123477677.warc^M
WARC-Record-ID: <urn:uuid:7b817fe0-d529-11e8-8ec6-391ee1fffcc8>^M
Content-Type: application/warc-fields^M
Content-Length: 379^M
^M
software: node-warc/2.1.0^M
format: WARC File Format 1.0^M
conformsTo: http://bibnum.bnf.fr/WARC/WARC_ISO_28500_version1_latestdraft.pdf^M
isPartOf: undefined^M
description: High fidelity preservation using Squidwarc^M
robots: ignore^M
http-header-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3563.0 Safari/537.36^M
^M
^M
^M
WARC/1.0^M
```

Versus this from a known-good WARC:

```
WARC/1.0^M
WARC-Type: warcinfo^M
WARC-Record-ID: <urn:uuid:fbd6cf0a-6160-4550-b343-12188dc05234>^M
WARC-Date: 2014-01-03T03:03:22Z^M
Content-Length: 196^M
Content-Type: application/warc-fields^M
WARC-Filename: live-20140103030321-wwwb-app5.us.archive.org.warc.gz^M
^M
software: LiveWeb Warc Writer 1.0^M
host: wwwb-app5.us.archive.org^M
isPartOf: liveweb^M
format: WARC file version 1.0^M
conformsTo: http://bibnum.bnf.fr/WARC/WARC_ISO_28500_version1_latestdraft.pdf^M
^M
^M
WARC/1.0^M
```

I'm not 100% sure what's going on, but there appears to be an extra newline at the end of all records except the `response` records. But it looks like all records end with 3 repeated `\r\n` (CRLF) newlines, so I suspect while the WARC record length is being recorded correctly for `response` records, the payload may have a `\r\n` appended.

The WARCs have no `WARC-Payload-Digest` so it's hard to tell if the payload matches the original response.

**Comment by N0taN3rd** [comment]
@machawk1 I think -e is what your looking for 
```
jwattools test [-beilx] [-w THREADS] [-a<yyyyMMddHHmmss>] <filepattern>...

test one or more ARC/WARC/GZip files

options:

 -a<yyyyMMddHHmmss>  only test files with last-modified after <yyyyMMddHHmmss>
 -b                  tag/rename files with errors/warnings (*.bad)
 -e                  show errors
 -i --ignore-digest  skip digest calculation and validation
 -l                  relaxed URL URI validation
 -x                  to validate text/xml payload (eg. mets)
 -w<x>               set the amount of worker thread(s) (defaults to 1)
```

**Comment by anjackson** [comment]
@machawk1 It's rather clumsy: you need the `-e` flag but the details are placed in the `i.out` file.

@N0taN3rd I'm not sure what's going on. It seems the responses you are getting are appending newlines after the `Content-length`, and then OWB relies on the `Content-length` to consume the record rather than skimming to the next record header?

**Comment by peterk** [comment]
Sorry for the late reply but I am still getting the same error with what I think is a newer version of node-warc, 3.0.0, (rebuilt everything today). Attaching a new file I used for the test.

[instagram.com_visit_berlin-11-19-2018_1542663033873.warc.zip](https://github.com/N0taN3rd/Squidwarc/files/2597285/instagram.com_visit_berlin-11-19-2018_1542663033873.warc.zip)

```
WARNING: Trying skip of failed record cleanup of {reader-identifier=/data/files1/instagram_old.warc, absolute-offset=0, WARC-Filename=instagram.com!visit_berlin-10-27-2018_1540650893910.warc, WARC-Date=2018-10-27T14:34:53Z, Content-Length=363, WARC-Record-ID=<urn:uuid:78138440-d9f5-11e8-a860-ffc684cdf206>, WARC-Type=warcinfo, Content-Type=application/warc-fields}: Unexpected character 57(Expecting d)
java.io.IOException: Unexpected character 57(Expecting d)
	at org.archive.io.warc.WARCReader.readExpectedChar(WARCReader.java:80)
	at org.archive.io.warc.WARCReader.gotoEOR(WARCReader.java:70)
	at org.archive.io.ArchiveReader.cleanupCurrentRecord(ArchiveReader.java:176)
	at org.archive.io.ArchiveReader$ArchiveRecordIterator.hasNext(ArchiveReader.java:449)
	at org.archive.wayback.resourcestore.indexer.ArchiveReaderCloseableIterator.hasNext(ArchiveReaderCloseableIterator.java:37)
	at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
	at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
	at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
	at org.archive.wayback.resourceindex.updater.IndexClient.addSearchResults(IndexClient.java:158)
	at org.archive.wayback.resourcestore.indexer.IndexWorker.doWork(IndexWorker.java:111)
	at org.archive.wayback.resourcestore.indexer.IndexWorker$WorkerThread.run(IndexWorker.java:244)
```

**Comment by peterk** [comment]
That sounds excellent! Thank you for all your work in this.

**Comment by peterk** [comment]
Tested on a couple of files and this works as expected now. Again, thank you!
