### ISSUE TITLE
Exception immediately thrown on first-run

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/Squidwarc#33]
### Are you submitting a **bug report** or a **feature request**?
Bug report.

### What is the current behavior?

Unable to get started using instructions in README. Per the README's Usage section, after cloning the repo I ran `npm install` then `./run-crawler.sh -c conf.json`. The console reported that an exception was thrown:
```
$ ./run-crawler.sh -c conf.json
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '../../node-warc/lib/writers/remoteChrome'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/private/tmp/Squidwarc/lib/crawler/chrome.js:18:35)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

### What is the expected behavior?
A crawl to be started (per Usage) or some more information to get started.

### What's your environment?

* Squidwarc d7792b8539bb28dd11950b9d14aa71324bb9c67e (latest master)
* macOS 10.14.1
* nodejs v10.12.0

**Comment by machawk1** [comment]
@N0taN3rd Running `bootstrap.sh` got me up and running. 👍 Feel free to close this ticket once you've updated the README. Hopefully anyone trying out Squidwarc will see this GitHub issue until then.

**Comment by machawk1** [comment]
@N0taN3rd I am not entirely familiar with using submodules in git, as used in bootstrap.sh. Would the initial `npm install` or `yarn` still be needed if the user was simply instructed to run the `bootstrap.sh` instead? It seems that in the bootstrap script the base (Squidwarc) dependencies are installed then the `node-warc` (submodule) dependencies.

I would make the change and submit a PR myself, except I do not want to introduce this redundancy.

**Comment by N0taN3rd** [comment]
@machawk1 that is correct. Bootstrap.sh was created to simplify the up and running process for Squidwarc running locally and in Docker. Any PR is welcome :)

**Comment by machawk1** [comment]
PR submitted in #34
